// Your First C++ Program

#include <iostream>
#include <string>
#include <cstdlib>

using namespace std;

int array11() {
	int user_input_a;
	cout << "Enter a score from 0 through 100 (negative number to end): ";
	cin >> user_input_a;
	
	return user_input_a;
	
}




int a28_min() {
	
	int user_input_a;
	cout << "Enter the minimum score from 0 through 100 (negative number to end): ";
	cin >> user_input_a;

	return user_input_a;
	
	
}

int a28_max() {
	
	int user_input_a;
	cout << "Enter the maximum score from 0 through 100 (negative number to end): ";
	cin >> user_input_a;

	return user_input_a;
	
	
}


//advanced 27
int array1() {
	
	int scores[20];
		
	//array of random nums
	for (int i = 0; i!=20;i++) {
		scores[i] = (rand()%101);
	}
	
	cout << "20 random numbers generated by C++" << endl;
	
	//loop to display the numbers
	for (int i = 0; i!=20; i++){
		cout << scores[i] << " ";
	}
	
	cout << endl << endl;
	
	
	int user_input_a = array11();
	
	
	if (user_input_a >= 0) {
		while (user_input_a >= 0) {
			int counter = 0;
			
			if (user_input_a <= 100) {
				for (int i = 0; i!=20; i++) {
					if (user_input_a == scores[i]) {		
						counter = counter + 1;
						} 
					} 
				cout << "Number of students earning a score of " << user_input_a << ": " << counter << endl;	
				user_input_a = array11(); 
			} else {
			
			while (user_input_a > 100) {
				cout << "EXCEEDS 100!!! PLEASE TRY AGAIN!!!" << endl;
				user_input_a = array11();
			} }
	} 	
		
		}
		
	//negative input go back to main menu
	if (user_input_a < 0) {
		return -1;
	} 
	
	return 0;
	
}



void a29_lottery() {
	int lottery[6];
	
	for (int i=0; i != 6; i++) {
		lottery[i] = 1 + (rand()%54);
	}
	
	cout << "Lottery numbers: ";
	for (int i = 0; i!=6; i++){
		 cout << lottery[i] << "  ";
	}
		
}


int advanced29(){
	
	int lottery[6];
	
	for (int i=0; i != 6; i++) {
		lottery[i] = 1 + (rand()%54);
	}
	
	cout << "Lottery numbers: ";
	for (int i = 0; i!=6; i++){
		 cout << lottery[i] << "  ";
	}
	
	
	string user_input;
	
	cout << endl << "Do you want to continue?[y/n]: ";
	cin >>  user_input;
	
			
	while (user_input == "y") {
		a29_lottery();
		cout << endl << "Do you want to continue?[y/n]: ";
		cin >>  user_input;
	} 
	
	if (user_input == "n") {
		return -1;
	} else {
		while (user_input != "y" && user_input != "n") {
			cout << "Invalid Input!!!" << endl;
			cout << "Please try again!!!" << endl;
			cout << endl << "Do you want to continue?[y/n]: ";
			cin >> user_input;
		}
		
		if (user_input == "y") {
			advanced29();
		} else if (user_input == "n") {
			return -1;
		}
		
		return -1;
		
	}
	
	
	
	
}



int advanced28() {
	
	int scores[20];
		
	//array of random nums
	for (int i = 0; i!=20;i++) {
		scores[i] = (rand()%101);
	}
	
	cout << "20 random numbers generated by C++" << endl;
	
	//loop to display the numbers
	for (int i = 0; i!=20; i++){
		cout << scores[i] << " ";
	}
	
	cout << endl << endl;
	
	int user_input_min = a28_min();
	int user_input_max = 0;
	
	int done = 0;
	
	while(user_input_min >= 0 && user_input_max >= 0) {
		
		if (done == 1) {
			user_input_min = a28_min();
			done = 0;
		}
		
		if (user_input_min >= 0) {
			if (user_input_min <= 100) {
				user_input_max = a28_max();
				
				if(user_input_max >= 0){
					if (user_input_max >= 0 ){
						if (user_input_max <= 100){
						
							int counter = 0;
							for (int i = 0; i!=20; i++) {
					
								if (user_input_min <= scores[i] && scores[i] <= user_input_max ){
								counter = counter + 1; 
								}
							}
							cout << "Number of students earning a score of " << user_input_min << ": " << counter << endl;
							done = 1;		
							
						} else {				
								while (user_input_max > 100) {
								cout << "EXCEEDS 100!!! PLEASE TRY AGAIN!!!" << endl;
								user_input_max = a28_max();
								}		
						}
						
					}
				} 
				
				
				
				
				
				
			} else {
				while (user_input_min > 100) {
				cout << "EXCEEDS 100!!! PLEASE TRY AGAIN!!!" << endl;
				user_input_min = a28_min();}
				}
		}
		
		
	}
	
	
	
	//negative input go back to main menu
	if (user_input_min < 0 || user_input_max < 0) {
		return -1;
	}
	
	return 0;
	
	
	
}

int main() {
	
	string choices[4] = {"a", "b", "c", "x"};
	
    cout << "[a] advanced27" << endl << "[b] advanced28" << endl << "[c] advanced29" << endl << "[x] exit" << endl << "Enter Option: "; 
    string user_input;
	cin >> user_input;
    
    int array_choice = 0;
    
    
    //advanced 27
    if(user_input == choices[0]) {
    	
    	//text
		cout << endl;
		cout << "Advanced 27" << endl;
		cout << "Enter the code that prompts the user to enter a score from 0 through 100." << endl;
		cout << "The program should display the number of students earning that score. " << endl;
		cout << "The 20 random scores (from 0-100)are initially generated by C++ " << endl;
		cout << "Use a sentinel value to end the program. " << endl << endl;
    	
    	array_choice = array1 ();
    	
    	//Go back to menu if input a negative number
    	if(array_choice == -1) {
    		main();
		}
	
	} else if(user_input == choices[1]) {
		//advanced28 text
		cout << endl;
		cout << "Advanced 28:" << endl;
		cout << "Write a program so that it prompts the user to enter a minimum score and a maximum score." << endl;
		cout << "The program should display the number of students who earned a score within that range." << endl;
		cout << "The 20 random scores (from 0-100)are initially generated by C++ " << endl;
		cout << "Use a sentinel value to end the program. " << endl << endl;
		
		array_choice = advanced28();
		
		//Go back to menu if input a negative number
		if(array_choice == -1) {
    		main();
		}
			
	} else if (user_input == choices[2]){
		//advanced29 text
		cout << endl;
		cout << "Advanced 29:" << endl;
		cout << "Create a program that generates and displays six unique random integers for a lottery game. " << endl;
		cout << "Each lottery number can range from 1 through 54 only." << endl;
		cout << "(Hint: Store the numbers in a one-dimensional array.)" << endl;
		cout << "Use a sentinel value to end the program." << endl << endl;
		
		
		array_choice = advanced29();
		if(array_choice == -1) {
			main();
		}
		
		
	} else if (user_input == choices[3]){
		cout << endl;
		cout << "END OF PROGRAM!!!!";
		
		return 0;
		
	}
	
	
	
    
    return 0;
    
}



